<a href="https://colab.research.google.com/github/R929RRJQ/coursera-test/blob/main/DHV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = c(1:5)
print(x)

[1] 1 2 3 4 5


In [ ]:
bool1 <- TRUE
print(bool1)

bool2 <- FALSE
print(bool2)

print(class(bool2))

[1] TRUE
[1] FALSE
[1] "logical"


In [ ]:
z = c(1,2,3,NA,4)
print(z)
print(is.na(z))

[1]  1  2  3 NA  4
[1] FALSE FALSE FALSE  TRUE FALSE


In [ ]:
clean <- complete.cases(z)
print(clean)
print(z[clean])

[1]  TRUE  TRUE  TRUE FALSE  TRUE
[1] 1 2 3 4


In [ ]:
print(0/0)

[1] NaN


In [ ]:
m <- c(2/3,3/3,0/0,1/0,0/1)
print(is.finite(m))
print(is.infinite(m))
print(is.nan(m))

[1]  TRUE  TRUE FALSE FALSE  TRUE
[1] FALSE FALSE FALSE  TRUE FALSE
[1] FALSE FALSE  TRUE FALSE FALSE


In [ ]:
mat <- matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3)
print(mat)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [ ]:
print(t(mat))

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6


In [ ]:
print(diag(3))

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


In [ ]:
zro <- matrix(rep(0,6),nrow = 2, ncol = 3)
print(zro)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0


In [ ]:
zro[2,3] = 9
print(zro)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    9


In [ ]:
print(mat)
print("Select 2nd row")
print(mat[2,])
print("Select 3rd column")
print(mat[,3])

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[1] "Select 2nd row"
[1] 2 4 6
[1] "Select 3rd column"
[1] 5 6


In [ ]:
matrix1 <- matrix(c(10,20,30,40,50,60,70,80,90),nrow = 3, ncol = 3)
print(matrix1)

     [,1] [,2] [,3]
[1,]   10   40   70
[2,]   20   50   80
[3,]   30   60   90


In [ ]:
print(matrix1[c(1,3),])

     [,1] [,2] [,3]
[1,]   10   40   70
[2,]   30   60   90


In [ ]:
matrix2 <- matrix1[,c(3,2,1)]

In [ ]:
print(matrix2)

     [,1] [,2] [,3]
[1,]   70   40   10
[2,]   80   50   20
[3,]   90   60   30
